### ISSUE TITLE
Bug: Cats do not use vertical movement texture data

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/community-rpg#11]
**Describe the bug**
Cats do not use the texture data for vertical movement. This data is included in their sprite sheets, but never used in-game:
![image](https://user-images.githubusercontent.com/36696816/165355300-c31c9c81-a28e-4c9d-ab8c-8b92c39a3b5f.png)

**To Reproduce**
1. Launch game
2. Watch until a cat decides to move up or down

**Expected behavior**
Texture data for vertical movement is used when moving up or down

**Comment by pushfoo** [comment]
This may also extend to NPCs in general, but we do not currently have any moving NPCs other than cats.

**Comment by Cleptomania** [comment]
A question that maybe makes sense for this, this is easy if it is only ever moving in one direction(left, right, up, down) but what happens when it's moving at an angle, say left and up at the same time, do we use the left facing or the up facing texture?

Obviously this could be solved by having textures for those angled directions, but those do not exist in the current spritesheet(at least for the cat specifically, but probably also for other characters). This can maybe be partially solved by switching some things to a more complete set of sprites from kenney.nl? We would definitely still have to build some logic in to handle the various directions other than left or right.

**Comment by pushfoo** [comment]
Building a more refined state and animation into the sprites is also worth considering. We hardcode frame numbers right now. :upside_down_face:

**Comment by bkiu** [comment]
I'm working on this.

**Comment by pushfoo** [comment]
Testing indicates that up and down data now gets used for cats and dogs. :+1:
